title: SQlab
description: Yuen/Nakazawa lab (結縁・中澤研究室)
e-affiliate: Dept. of Computing and Software Science, Graduate School of Informatics, Nagoya University
j-affiliate: 名古屋大学大学院情報学研究科情報システム学専攻
e-postalAddress: Furo-cho, Chikusa-ku, Nagoya, Japan  4648601
j-postalAddress: 〒4648601 名古屋市千種区不老町
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
